import headphonesImg from '@/assets/products/headphones.jpg';
import bagImg from '@/assets/products/bag.jpg';
import watchImg from '@/assets/products/watch.jpg';
import sunglassesImg from '@/assets/products/sunglasses.jpg';
import sneakersImg from '@/assets/products/sneakers.jpg';
import perfumeImg from '@/assets/products/perfume.jpg';
import phoneImg from '@/assets/products/phone.jpg';
import scarfImg from '@/assets/products/scarf.jpg';

export interface Store {
  id: string;
  nameEn: string;
  nameAr: string;
  emoji: string;
  descriptionEn: string;
  descriptionAr: string;
  categoryEn: string;
  categoryAr: string;
}

export interface Product {
  id: string;
  nameEn: string;
  nameAr: string;
  price: number;
  originalPrice?: number;
  descriptionEn: string;
  descriptionAr: string;
  storeId: string;
  storeNameEn: string;
  storeNameAr: string;
  image: string;
  /** Platform-level category (controlled by admin) */
  categoryEn: string;
  categoryAr: string;
  /** Store-specific category ID (controlled by store owner) */
  storeCategoryId: string;
  /** Sub-category hashtags used for "Related Topics" discovery */
  tags: string[];
  rating: number;
  reviewCount: number;
  isNew?: boolean;
  isFeatured?: boolean;
}

/**
 * Categories that share thematic overlap — drives "Explore Related Categories"
 * on the dedicated category page.
 */
export const RELATED_CATEGORIES: Record<string, string[]> = {
  Electronics: ['Watches'],
  Watches: ['Electronics', 'Accessories'],
  Accessories: ['Fashion', 'Shoes'],
  Shoes: ['Fashion', 'Accessories'],
  Perfumes: ['Accessories'],
  Fashion: ['Shoes', 'Accessories'],
};

// ─── Store-Specific Categories ────────────────────────────────────────────────
//
// Two-level category system:
//   • Platform categories  (e.g. Electronics, Perfumes) → controlled by the
//     platform admin; shared across all stores.
//   • Store-specific categories → controlled by each store owner; only visible
//     within that store's catalog page.

export interface StoreSpecificCategory {
  id: string;
  storeId: string;
  nameEn: string;
  nameAr: string;
  emoji: string;
}

export const STORE_SPECIFIC_CATEGORIES: Record<string, StoreSpecificCategory[]> = {
  techzone: [
    { id: 'tc-phones',    storeId: 'techzone',      nameEn: 'Smartphones',  nameAr: 'هواتف ذكية',                  emoji: '📱' },
    { id: 'tc-audio',     storeId: 'techzone',      nameEn: 'Audio & Sound', nameAr: 'صوت وسماعات',                emoji: '🎧' },
    { id: 'tc-wearables', storeId: 'techzone',      nameEn: 'Wearables',    nameAr: 'أجهزة قابلة للارتداء',        emoji: '⌚' },
  ],
  'leather-house': [
    { id: 'lh-bags',    storeId: 'leather-house', nameEn: 'Bags & Totes', nameAr: 'حقائب',   emoji: '👜' },
    { id: 'lh-wallets', storeId: 'leather-house', nameEn: 'Wallets',      nameAr: 'محافظ',   emoji: '👛' },
  ],
  'time-gallery': [
    { id: 'tg-gold',   storeId: 'time-gallery', nameEn: 'Gold Collection',   nameAr: 'المجموعة الذهبية', emoji: '🥇' },
    { id: 'tg-silver', storeId: 'time-gallery', nameEn: 'Silver Collection', nameAr: 'المجموعة الفضية',  emoji: '🥈' },
  ],
  'optic-style': [
    { id: 'os-sun', storeId: 'optic-style', nameEn: 'Sunglasses', nameAr: 'نظارات شمسية', emoji: '🕶️' },
  ],
  'step-up': [
    { id: 'su-casual', storeId: 'step-up', nameEn: 'Casual & Sneakers', nameAr: 'كاجوال ورياضي', emoji: '👟' },
    { id: 'su-formal', storeId: 'step-up', nameEn: 'Formal',            nameAr: 'رسمي',          emoji: '👞' },
    { id: 'su-sport',  storeId: 'step-up', nameEn: 'Sport & Running',   nameAr: 'رياضة وجري',   emoji: '🏃' },
  ],
  'scent-palace': [
    { id: 'sp-mens',   storeId: 'scent-palace', nameEn: "Men's Perfumes",    nameAr: 'عطور رجالية', emoji: '🧴' },
    { id: 'sp-womens', storeId: 'scent-palace', nameEn: "Women's Perfumes",  nameAr: 'عطور نسائية', emoji: '🌸' },
    { id: 'sp-kids',   storeId: 'scent-palace', nameEn: "Kids' Fragrances",  nameAr: 'عطور أطفال', emoji: '🧒' },
  ],
  'cozy-corner': [
    { id: 'cc-winter', storeId: 'cozy-corner', nameEn: 'Winter Collection', nameAr: 'مجموعة شتوية',  emoji: '🧣' },
    { id: 'cc-casual', storeId: 'cozy-corner', nameEn: 'Casual Wear',       nameAr: 'ملابس كاجوال', emoji: '👕' },
  ],
};

// ─── Advertisement Carousel Data ──────────────────────────────────────────────

export interface Ad {
  id: string;
  titleEn: string;
  titleAr: string;
  subtitleEn: string;
  subtitleAr: string;
  ctaEn: string;
  ctaAr: string;
  emoji: string;
  /** Tailwind gradient utility applied to the card background */
  gradient: string;
  /** Optional navigation target when the user clicks the ad */
  linkType?: 'category' | 'store';
  linkValue?: string;
}

export const MOCK_ADS: Ad[] = [
  {
    id: 'ad-1',
    titleEn: 'Up to 40% Off Electronics',
    titleAr: 'خصم يصل إلى 40% على الإلكترونيات',
    subtitleEn: 'Latest gadgets at unbeatable prices — limited time!',
    subtitleAr: 'أحدث الأجهزة بأسعار لا تُضاهى — لفترة محدودة!',
    ctaEn: 'Shop Electronics',
    ctaAr: 'تسوق الإلكترونيات',
    emoji: '⚡',
    gradient: 'from-blue-600 to-indigo-700',
    linkType: 'category',
    linkValue: 'Electronics',
  },
  {
    id: 'ad-2',
    titleEn: 'Luxury Fragrances — New Arrivals',
    titleAr: 'عطور فاخرة — وصول جديد',
    subtitleEn: 'Discover exclusive Arabian scents crafted for royalty.',
    subtitleAr: 'اكتشف عطوراً عربية حصرية مُصنَّعة للملوك.',
    ctaEn: 'Explore Perfumes',
    ctaAr: 'استكشف العطور',
    emoji: '🌸',
    gradient: 'from-pink-500 to-rose-600',
    linkType: 'category',
    linkValue: 'Perfumes',
  },
  {
    id: 'ad-3',
    titleEn: 'Premium Watches — Swiss Made',
    titleAr: 'ساعات فاخرة — صناعة سويسرية',
    subtitleEn: 'Timeless elegance for every wrist. Explore our collection.',
    subtitleAr: 'أناقة خالدة لكل معصم. استعرض مجموعتنا.',
    ctaEn: 'View Watches',
    ctaAr: 'تصفح الساعات',
    emoji: '🕰️',
    gradient: 'from-amber-500 to-yellow-600',
    linkType: 'category',
    linkValue: 'Watches',
  },
  {
    id: 'ad-4',
    titleEn: 'Step Up — Footwear for Every Occasion',
    titleAr: 'ستيب أب — أحذية لكل مناسبة',
    subtitleEn: 'From casual sneakers to formal Oxfords. Find your perfect pair.',
    subtitleAr: 'من الأحذية الرياضية إلى الأوكسفورد الرسمي. اعثر على زوجك المثالي.',
    ctaEn: 'Shop Shoes',
    ctaAr: 'تسوق الأحذية',
    emoji: '👟',
    gradient: 'from-green-500 to-teal-600',
    linkType: 'category',
    linkValue: 'Shoes',
  },
  {
    id: 'ad-5',
    titleEn: 'Fashion & Knitwear — New Season',
    titleAr: 'أزياء وتريكو — موسم جديد',
    subtitleEn: 'Stay cozy and stylish with our latest winter collection.',
    subtitleAr: 'ابقَ دافئاً وأنيقاً مع أحدث مجموعة شتوية.',
    ctaEn: 'Explore Fashion',
    ctaAr: 'استكشف الأزياء',
    emoji: '🧣',
    gradient: 'from-orange-500 to-red-500',
    linkType: 'category',
    linkValue: 'Fashion',
  },
];

// ─── Store-Specific Carousel Ads ──────────────────────────────────────────────

export const STORE_ADS: Record<string, Ad[]> = {
  techzone: [
    {
      id: 'tz-1',
      titleEn: 'TechZone — Flash Sale: 30% Off',
      titleAr: 'تك زون — تخفيضات فلاش: 30% خصم',
      subtitleEn: 'Grab the hottest gadgets before stock runs out!',
      subtitleAr: 'احصل على أحدث الأجهزة قبل نفاد المخزون!',
      ctaEn: 'Shop Now',
      ctaAr: 'تسوق الآن',
      emoji: '⚡',
      gradient: 'from-blue-600 to-cyan-600',
      linkType: 'store',
      linkValue: 'techzone',
    },
    {
      id: 'tz-2',
      titleEn: 'New: True Wireless Earbuds',
      titleAr: 'جديد: سماعات لاسلكية TWS',
      subtitleEn: '28-hour battery • IPX5 sweat-proof • Crystal clear sound.',
      subtitleAr: '28 ساعة بطارية • مقاومة العرق • صوت بلوري نقي.',
      ctaEn: 'Explore Audio',
      ctaAr: 'استكشف الصوتيات',
      emoji: '🎧',
      gradient: 'from-indigo-600 to-violet-700',
      linkType: 'store',
      linkValue: 'techzone',
    },
  ],
  'leather-house': [
    {
      id: 'lh-1',
      titleEn: 'Leather House — Handcrafted Luxury',
      titleAr: 'بيت الجلود — فخامة صنوعة يدوياً',
      subtitleEn: 'Every stitch tells a story. Genuine leather, timeless style.',
      subtitleAr: 'كل غرزة تحكي قصة. جلد أصيل، أناقة خالدة.',
      ctaEn: 'Browse Bags',
      ctaAr: 'تصفح الحقائب',
      emoji: '👜',
      gradient: 'from-amber-700 to-yellow-800',
      linkType: 'store',
      linkValue: 'leather-house',
    },
    {
      id: 'lh-2',
      titleEn: 'Slim Wallets — RFID Protected',
      titleAr: 'محافظ رفيعة — حماية RFID',
      subtitleEn: 'Carry less, live more. Full-grain leather bifold wallets.',
      subtitleAr: 'احمل أقل، عش أكثر. محافظ جلد طبيعي رفيعة.',
      ctaEn: 'Shop Wallets',
      ctaAr: 'تسوق المحافظ',
      emoji: '👛',
      gradient: 'from-stone-600 to-amber-800',
      linkType: 'store',
      linkValue: 'leather-house',
    },
  ],
  'time-gallery': [
    {
      id: 'tg-1',
      titleEn: 'Time Gallery — Gold Collection',
      titleAr: 'معرض الوقت — المجموعة الذهبية',
      subtitleEn: 'Swiss movement. Sapphire crystal. Timeless elegance.',
      subtitleAr: 'حركة سويسرية. كريستال ياقوتي. أناقة خالدة.',
      ctaEn: 'View Gold Watches',
      ctaAr: 'عرض الساعات الذهبية',
      emoji: '🥇',
      gradient: 'from-yellow-500 to-amber-600',
      linkType: 'store',
      linkValue: 'time-gallery',
    },
    {
      id: 'tg-2',
      titleEn: 'Silver Edition — Water Resistant',
      titleAr: 'الإصدار الفضي — مقاوم للماء',
      subtitleEn: 'Minimalist design, maximum precision. Up to 50m water resistance.',
      subtitleAr: 'تصميم بسيط، دقة قصوى. مقاوم للماء حتى 50م.',
      ctaEn: 'View Silver Watches',
      ctaAr: 'عرض الساعات الفضية',
      emoji: '🥈',
      gradient: 'from-slate-500 to-gray-700',
      linkType: 'store',
      linkValue: 'time-gallery',
    },
  ],
  'optic-style': [
    {
      id: 'os-1',
      titleEn: 'Optic Style — See the World Differently',
      titleAr: 'أوبتك ستايل — انظر للعالم بشكل مختلف',
      subtitleEn: 'UV400 polarized sunglasses. Lightweight. Iconic.',
      subtitleAr: 'نظارات شمسية مستقطبة UV400. خفيفة. أيقونية.',
      ctaEn: 'Shop Eyewear',
      ctaAr: 'تسوق النظارات',
      emoji: '🕶️',
      gradient: 'from-violet-600 to-purple-700',
      linkType: 'store',
      linkValue: 'optic-style',
    },
  ],
  'step-up': [
    {
      id: 'su-1',
      titleEn: 'Step Up — Walk in Style',
      titleAr: 'ستيب أب — امشِ بأناقة',
      subtitleEn: 'Sneakers, oxfords, and runners for every occasion.',
      subtitleAr: 'أحذية رياضية وأوكسفورد وجري لكل مناسبة.',
      ctaEn: 'Shop All Shoes',
      ctaAr: 'تسوق جميع الأحذية',
      emoji: '👟',
      gradient: 'from-green-600 to-emerald-700',
      linkType: 'store',
      linkValue: 'step-up',
    },
    {
      id: 'su-2',
      titleEn: 'New: Sport Running Collection',
      titleAr: 'جديد: مجموعة الجري الرياضي',
      subtitleEn: 'Lightweight. Breathable. Built for performance.',
      subtitleAr: 'خفيفة. قابلة للتنفس. مصممة للأداء العالي.',
      ctaEn: 'Explore Running',
      ctaAr: 'استكشف الجري',
      emoji: '🏃',
      gradient: 'from-teal-500 to-green-700',
      linkType: 'store',
      linkValue: 'step-up',
    },
  ],
  'scent-palace': [
    {
      id: 'sp-1',
      titleEn: 'Scent Palace — Arabian Oud Collection',
      titleAr: 'قصر العطور — مجموعة العود العربي',
      subtitleEn: 'Rich oud blended with amber and sandalwood. A royal experience.',
      subtitleAr: 'عود غني ممزوج بالعنبر وخشب الصندل. تجربة ملكية.',
      ctaEn: 'Shop Oud',
      ctaAr: 'تسوق العود',
      emoji: '🧴',
      gradient: 'from-rose-700 to-pink-800',
      linkType: 'store',
      linkValue: 'scent-palace',
    },
    {
      id: 'sp-2',
      titleEn: 'New Season — Women\'s & Kids\' Fragrances',
      titleAr: 'موسم جديد — عطور نسائية وأطفال',
      subtitleEn: 'Delicate floral musks and gentle kids\' colognes.',
      subtitleAr: 'مسكات زهرية رقيقة وعطور أطفال لطيفة.',
      ctaEn: 'Explore Fragrances',
      ctaAr: 'استكشف العطور',
      emoji: '🌸',
      gradient: 'from-pink-500 to-rose-600',
      linkType: 'store',
      linkValue: 'scent-palace',
    },
  ],
  'cozy-corner': [
    {
      id: 'cc-1',
      titleEn: 'Cozy Corner — Winter Collection',
      titleAr: 'الركن الدافئ — مجموعة الشتاء',
      subtitleEn: 'Soft merino wool scarves and knitwear for cold days.',
      subtitleAr: 'وشاحات صوف ميرينو ناعمة وتريكو دافئ لأيام البرد.',
      ctaEn: 'Shop Winter',
      ctaAr: 'تسوق الشتاء',
      emoji: '🧣',
      gradient: 'from-orange-600 to-red-700',
      linkType: 'store',
      linkValue: 'cozy-corner',
    },
    {
      id: 'cc-2',
      titleEn: 'Casual Denim — Timeless Wardrobe',
      titleAr: 'دينيم كاجوال — خزانة ملابس خالدة',
      subtitleEn: 'Classic straight-cut denim jackets. Always in style.',
      subtitleAr: 'جاكيتات دينيم بقصة مستقيمة كلاسيكية. دائماً في الموضة.',
      ctaEn: 'Explore Casual',
      ctaAr: 'استكشف الكاجوال',
      emoji: '👕',
      gradient: 'from-amber-500 to-orange-600',
      linkType: 'store',
      linkValue: 'cozy-corner',
    },
  ],
};

// ─── Category-Specific Carousel Ads ──────────────────────────────────────────

export const CATEGORY_ADS: Record<string, Ad[]> = {
  Electronics: [
    {
      id: 'cat-elec-1',
      titleEn: 'Electronics — Up to 40% Off',
      titleAr: 'إلكترونيات — خصم يصل إلى 40%',
      subtitleEn: 'Phones, earbuds, wearables and more — at unbeatable prices.',
      subtitleAr: 'هواتف، سماعات، أجهزة ذكية والمزيد — بأسعار لا تُضاهى.',
      ctaEn: 'Shop Electronics',
      ctaAr: 'تسوق الإلكترونيات',
      emoji: '⚡',
      gradient: 'from-blue-600 to-indigo-700',
      linkType: 'category',
      linkValue: 'Electronics',
    },
    {
      id: 'cat-elec-2',
      titleEn: 'New Arrivals: Wearable Tech',
      titleAr: 'وصل حديثاً: أجهزة قابلة للارتداء',
      subtitleEn: 'Smart fitness bands, TWS earbuds, and flagship phones.',
      subtitleAr: 'أساور لياقة ذكية، سماعات TWS، وهواتف رائدة.',
      ctaEn: 'Discover Now',
      ctaAr: 'اكتشف الآن',
      emoji: '📱',
      gradient: 'from-cyan-500 to-blue-600',
      linkType: 'category',
      linkValue: 'Electronics',
    },
  ],
  Accessories: [
    {
      id: 'cat-acc-1',
      titleEn: 'Accessories — Curated Collections',
      titleAr: 'إكسسوارات — مجموعات مختارة',
      subtitleEn: 'Bags, eyewear, wallets — handpicked for you.',
      subtitleAr: 'حقائب، نظارات، محافظ — مختارة خصيصاً لك.',
      ctaEn: 'Browse Accessories',
      ctaAr: 'تصفح الإكسسوارات',
      emoji: '💎',
      gradient: 'from-purple-600 to-violet-700',
      linkType: 'category',
      linkValue: 'Accessories',
    },
    {
      id: 'cat-acc-2',
      titleEn: 'Leather Goods — New Season',
      titleAr: 'منتجات جلدية — موسم جديد',
      subtitleEn: 'Premium full-grain leather bags and RFID wallets.',
      subtitleAr: 'حقائب جلد طبيعي فاخرة ومحافظ مع حماية RFID.',
      ctaEn: 'Explore Leather',
      ctaAr: 'استكشف الجلود',
      emoji: '👜',
      gradient: 'from-violet-500 to-purple-700',
      linkType: 'category',
      linkValue: 'Accessories',
    },
  ],
  Watches: [
    {
      id: 'cat-wat-1',
      titleEn: 'Luxury Watches — Swiss Precision',
      titleAr: 'ساعات فاخرة — دقة سويسرية',
      subtitleEn: 'Gold and silver timepieces crafted for the discerning.',
      subtitleAr: 'ساعات ذهبية وفضية مُصنَّعة لذوي الذوق الرفيع.',
      ctaEn: 'View Watches',
      ctaAr: 'تصفح الساعات',
      emoji: '🕰️',
      gradient: 'from-amber-500 to-yellow-600',
      linkType: 'category',
      linkValue: 'Watches',
    },
    {
      id: 'cat-wat-2',
      titleEn: 'Minimalist Silver Edition',
      titleAr: 'الإصدار الفضي البسيط',
      subtitleEn: 'Slim profile. Sapphire glass. Water resistant to 50m.',
      subtitleAr: 'حجم رفيع. زجاج ياقوتي. مقاوم للماء حتى 50م.',
      ctaEn: 'Shop Now',
      ctaAr: 'تسوق الآن',
      emoji: '⌚',
      gradient: 'from-slate-500 to-yellow-700',
      linkType: 'category',
      linkValue: 'Watches',
    },
  ],
  Shoes: [
    {
      id: 'cat-sho-1',
      titleEn: 'Footwear — Every Occasion',
      titleAr: 'أحذية — لكل مناسبة',
      subtitleEn: 'Casual sneakers, formal oxfords, and sport runners.',
      subtitleAr: 'أحذية رياضية كاجوال، أوكسفورد رسمية، وأحذية جري.',
      ctaEn: 'Shop Shoes',
      ctaAr: 'تسوق الأحذية',
      emoji: '👟',
      gradient: 'from-green-600 to-teal-700',
      linkType: 'category',
      linkValue: 'Shoes',
    },
    {
      id: 'cat-sho-2',
      titleEn: 'Sport Running — New Collection',
      titleAr: 'الجري الرياضي — مجموعة جديدة',
      subtitleEn: 'Lightweight. Breathable. Responsive cushioning.',
      subtitleAr: 'خفيفة. قابلة للتنفس. تبطين متجاوب.',
      ctaEn: 'Explore Running',
      ctaAr: 'استكشف الجري',
      emoji: '🏃',
      gradient: 'from-emerald-500 to-green-700',
      linkType: 'category',
      linkValue: 'Shoes',
    },
  ],
  Perfumes: [
    {
      id: 'cat-per-1',
      titleEn: 'Arabian Fragrances — New Arrivals',
      titleAr: 'عطور عربية — وصول جديد',
      subtitleEn: 'Exclusive oud, musk, and floral scents from Scent Palace.',
      subtitleAr: 'عطور عود وتشك وزهرية حصرية من قصر العطور.',
      ctaEn: 'Explore Perfumes',
      ctaAr: 'استكشف العطور',
      emoji: '🌸',
      gradient: 'from-pink-600 to-rose-700',
      linkType: 'category',
      linkValue: 'Perfumes',
    },
    {
      id: 'cat-per-2',
      titleEn: 'Kids\' Fragrances — Gentle & Safe',
      titleAr: 'عطور الأطفال — لطيفة وآمنة',
      subtitleEn: 'Light floral and fruity scents designed for little ones.',
      subtitleAr: 'عطور زهرية وفاكهية خفيفة مُصممة للأطفال.',
      ctaEn: 'Shop Kids\' Scents',
      ctaAr: 'تسوق عطور الأطفال',
      emoji: '🧒',
      gradient: 'from-rose-400 to-pink-600',
      linkType: 'category',
      linkValue: 'Perfumes',
    },
  ],
  Fashion: [
    {
      id: 'cat-fas-1',
      titleEn: 'Fashion — New Winter Season',
      titleAr: 'أزياء — موسم الشتاء الجديد',
      subtitleEn: 'Cozy knitwear, denim, and more — stay stylish all season.',
      subtitleAr: 'تريكو دافئ، دينيم، والمزيد — ابقَ أنيقاً طوال الموسم.',
      ctaEn: 'Explore Fashion',
      ctaAr: 'استكشف الأزياء',
      emoji: '👗',
      gradient: 'from-orange-500 to-red-600',
      linkType: 'category',
      linkValue: 'Fashion',
    },
    {
      id: 'cat-fas-2',
      titleEn: 'Classic Denim — Timeless Style',
      titleAr: 'دينيم كلاسيكي — أناقة خالدة',
      subtitleEn: 'Straight-cut denim jackets. A wardrobe essential.',
      subtitleAr: 'جاكيتات دينيم بقصة مستقيمة. أساسي في كل خزانة.',
      ctaEn: 'Shop Denim',
      ctaAr: 'تسوق الدينيم',
      emoji: '🧣',
      gradient: 'from-red-500 to-orange-600',
      linkType: 'category',
      linkValue: 'Fashion',
    },
  ],
};

export const MOCK_STORES: Store[] = [
  {
    id: 'techzone',
    nameEn: 'TechZone',
    nameAr: 'تك زون',
    emoji: '⚡',
    descriptionEn: 'Latest gadgets & electronics',
    descriptionAr: 'أحدث الأجهزة والإلكترونيات',
    categoryEn: 'Electronics',
    categoryAr: 'إلكترونيات',
  },
  {
    id: 'leather-house',
    nameEn: 'Leather House',
    nameAr: 'بيت الجلود',
    emoji: '👜',
    descriptionEn: 'Handcrafted leather goods',
    descriptionAr: 'منتجات جلدية مصنوعة يدوياً',
    categoryEn: 'Accessories',
    categoryAr: 'إكسسوارات',
  },
  {
    id: 'time-gallery',
    nameEn: 'Time Gallery',
    nameAr: 'معرض الوقت',
    emoji: '🕰️',
    descriptionEn: 'Luxury watches & timepieces',
    descriptionAr: 'ساعات فاخرة وأجهزة قياس الوقت',
    categoryEn: 'Watches',
    categoryAr: 'ساعات',
  },
  {
    id: 'optic-style',
    nameEn: 'Optic Style',
    nameAr: 'أوبتك ستايل',
    emoji: '🕶️',
    descriptionEn: 'Premium eyewear & sunglasses',
    descriptionAr: 'نظارات فاخرة وواقية من الشمس',
    categoryEn: 'Accessories',
    categoryAr: 'إكسسوارات',
  },
  {
    id: 'step-up',
    nameEn: 'Step Up',
    nameAr: 'ستيب أب',
    emoji: '👟',
    descriptionEn: 'Footwear for every occasion',
    descriptionAr: 'أحذية لكل مناسبة',
    categoryEn: 'Shoes',
    categoryAr: 'أحذية',
  },
  {
    id: 'scent-palace',
    nameEn: 'Scent Palace',
    nameAr: 'قصر العطور',
    emoji: '🌸',
    descriptionEn: 'Exquisite Arabian fragrances',
    descriptionAr: 'عطور عربية فاخرة',
    categoryEn: 'Perfumes',
    categoryAr: 'عطور',
  },
  {
    id: 'cozy-corner',
    nameEn: 'Cozy Corner',
    nameAr: 'الركن الدافئ',
    emoji: '🧣',
    descriptionEn: 'Cozy fashion & knitwear',
    descriptionAr: 'ملابس دافئة وأزياء مريحة',
    categoryEn: 'Fashion',
    categoryAr: 'أزياء',
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    nameEn: 'Premium Wireless Headphones',
    nameAr: 'سماعات لاسلكية فاخرة',
    price: 299,
    originalPrice: 399,
    descriptionEn: 'High-fidelity sound with active noise cancellation and 30-hour battery life.',
    descriptionAr: 'صوت عالي الدقة مع إلغاء الضوضاء النشط وعمر بطارية 30 ساعة.',
    storeId: 'techzone',
    storeNameEn: 'TechZone',
    storeNameAr: 'تك زون',
    image: headphonesImg,
    categoryEn: 'Electronics',
    categoryAr: 'إلكترونيات',
    storeCategoryId: 'tc-audio',
    tags: ['wireless', 'audio', 'noise-cancellation'],
    rating: 4.8,
    reviewCount: 312,
    isFeatured: true,
  },
  {
    id: '2',
    nameEn: 'Leather Messenger Bag',
    nameAr: 'حقيبة جلدية كلاسيكية',
    price: 189,
    descriptionEn: 'Handcrafted genuine leather bag with brass buckles and adjustable strap.',
    descriptionAr: 'حقيبة جلد طبيعي مصنوعة يدوياً مع إبزيمات نحاسية وحزام قابل للتعديل.',
    storeId: 'leather-house',
    storeNameEn: 'Leather House',
    storeNameAr: 'بيت الجلود',
    image: bagImg,
    categoryEn: 'Accessories',
    categoryAr: 'إكسسوارات',
    storeCategoryId: 'lh-bags',
    tags: ['leather', 'bags', 'handcrafted'],
    rating: 4.6,
    reviewCount: 178,
    isNew: true,
  },
  {
    id: '3',
    nameEn: 'Gold Wristwatch',
    nameAr: 'ساعة يد ذهبية',
    price: 459,
    originalPrice: 599,
    descriptionEn: 'Elegant gold-plated timepiece with sapphire crystal and Swiss movement.',
    descriptionAr: 'ساعة أنيقة مطلية بالذهب مع كريستال ياقوتي وحركة سويسرية.',
    storeId: 'time-gallery',
    storeNameEn: 'Time Gallery',
    storeNameAr: 'معرض الوقت',
    image: watchImg,
    categoryEn: 'Watches',
    categoryAr: 'ساعات',
    storeCategoryId: 'tg-gold',
    tags: ['luxury', 'gold', 'swiss-made'],
    rating: 4.9,
    reviewCount: 94,
    isFeatured: true,
  },
  {
    id: '4',
    nameEn: 'Aviator Sunglasses',
    nameAr: 'نظارات شمسية أفياتور',
    price: 129,
    originalPrice: 179,
    descriptionEn: 'UV400 protection with polarized lenses and lightweight gold frame.',
    descriptionAr: 'حماية UV400 مع عدسات مستقطبة وإطار ذهبي خفيف الوزن.',
    storeId: 'optic-style',
    storeNameEn: 'Optic Style',
    storeNameAr: 'أوبتك ستايل',
    image: sunglassesImg,
    categoryEn: 'Accessories',
    categoryAr: 'إكسسوارات',
    storeCategoryId: 'os-sun',
    tags: ['eyewear', 'uv-protection', 'polarized'],
    rating: 4.5,
    reviewCount: 241,
    isFeatured: true,
  },
  {
    id: '5',
    nameEn: 'Classic White Sneakers',
    nameAr: 'حذاء رياضي أبيض كلاسيكي',
    price: 159,
    descriptionEn: 'Premium leather sneakers with cushioned sole for all-day comfort.',
    descriptionAr: 'حذاء رياضي جلد فاخر مع نعل مبطن لراحة طوال اليوم.',
    storeId: 'step-up',
    storeNameEn: 'Step Up',
    storeNameAr: 'ستيب أب',
    image: sneakersImg,
    categoryEn: 'Shoes',
    categoryAr: 'أحذية',
    storeCategoryId: 'su-casual',
    tags: ['casual', 'sneakers', 'leather-shoes'],
    rating: 4.4,
    reviewCount: 389,
    isNew: true,
  },
  {
    id: '6',
    nameEn: 'Arabian Oud Perfume',
    nameAr: 'عطر عود عربي',
    price: 219,
    originalPrice: 279,
    descriptionEn: 'Rich oud fragrance blended with amber and sandalwood notes.',
    descriptionAr: 'عطر عود غني ممزوج بنفحات العنبر وخشب الصندل.',
    storeId: 'scent-palace',
    storeNameEn: 'Scent Palace',
    storeNameAr: 'قصر العطور',
    image: perfumeImg,
    categoryEn: 'Perfumes',
    categoryAr: 'عطور',
    storeCategoryId: 'sp-mens',
    tags: ['arabic-fragrance', 'oud', 'mens-perfume'],
    rating: 4.7,
    reviewCount: 156,
    isFeatured: true,
  },
  {
    id: '7',
    nameEn: 'Flagship Smartphone',
    nameAr: 'هاتف ذكي رائد',
    price: 899,
    originalPrice: 1099,
    descriptionEn: 'Latest flagship with 6.7" AMOLED display and 108MP camera.',
    descriptionAr: 'أحدث هاتف رائد بشاشة AMOLED 6.7 بوصة وكاميرا 108 ميجابكسل.',
    storeId: 'techzone',
    storeNameEn: 'TechZone',
    storeNameAr: 'تك زون',
    image: phoneImg,
    categoryEn: 'Electronics',
    categoryAr: 'إلكترونيات',
    storeCategoryId: 'tc-phones',
    tags: ['flagship', 'smartphone', 'amoled'],
    rating: 4.9,
    reviewCount: 521,
    isFeatured: true,
  },
  {
    id: '8',
    nameEn: 'Wool Knitted Scarf',
    nameAr: 'وشاح صوف محبوك',
    price: 69,
    descriptionEn: 'Soft merino wool scarf in a warm camel tone, perfect for winter.',
    descriptionAr: 'وشاح صوف ميرينو ناعم بلون جملي دافئ، مثالي للشتاء.',
    storeId: 'cozy-corner',
    storeNameEn: 'Cozy Corner',
    storeNameAr: 'الركن الدافئ',
    image: scarfImg,
    categoryEn: 'Fashion',
    categoryAr: 'أزياء',
    storeCategoryId: 'cc-winter',
    tags: ['winter', 'knitwear', 'wool'],
    rating: 4.3,
    reviewCount: 87,
    isNew: true,
  },
  {
    id: '9',
    nameEn: 'Smart Fitness Band',
    nameAr: 'سوار لياقة ذكي',
    price: 149,
    originalPrice: 199,
    descriptionEn: 'Track heart rate, sleep, steps and receive smart notifications all day.',
    descriptionAr: 'تتبع معدل ضربات القلب والنوم والخطوات واستقبل الإشعارات الذكية طوال اليوم.',
    storeId: 'techzone',
    storeNameEn: 'TechZone',
    storeNameAr: 'تك زون',
    image: headphonesImg,
    categoryEn: 'Electronics',
    categoryAr: 'إلكترونيات',
    storeCategoryId: 'tc-wearables',
    tags: ['wearables', 'fitness', 'smartwatch'],
    rating: 4.5,
    reviewCount: 203,
    isNew: true,
  },
  {
    id: '10',
    nameEn: 'Rose Musk Perfume',
    nameAr: 'عطر المسك الوردي',
    price: 169,
    descriptionEn: 'Delicate floral musk with hints of rose and white amber — a timeless classic.',
    descriptionAr: 'مسك زهري رقيق بلمسات من الورد والعنبر الأبيض — كلاسيكي خالد.',
    storeId: 'scent-palace',
    storeNameEn: 'Scent Palace',
    storeNameAr: 'قصر العطور',
    image: perfumeImg,
    categoryEn: 'Perfumes',
    categoryAr: 'عطور',
    storeCategoryId: 'sp-womens',
    tags: ['floral', 'musk', 'womens-perfume'],
    rating: 4.6,
    reviewCount: 112,
  },
  {
    id: '11',
    nameEn: 'Silver Minimalist Watch',
    nameAr: 'ساعة فضية بسيطة',
    price: 289,
    originalPrice: 349,
    descriptionEn: 'Slim stainless-steel case with sapphire glass, water-resistant to 50m.',
    descriptionAr: 'هيكل رفيع من الفولاذ المقاوم للصدأ مع زجاج ياقوتي، مقاوم للماء حتى 50م.',
    storeId: 'time-gallery',
    storeNameEn: 'Time Gallery',
    storeNameAr: 'معرض الوقت',
    image: watchImg,
    categoryEn: 'Watches',
    categoryAr: 'ساعات',
    storeCategoryId: 'tg-silver',
    tags: ['minimalist', 'slim', 'everyday'],
    rating: 4.7,
    reviewCount: 64,
    isNew: true,
  },
  {
    id: '12',
    nameEn: 'Leather Wallet',
    nameAr: 'محفظة جلدية',
    price: 89,
    descriptionEn: 'Slim full-grain leather bifold wallet with RFID protection.',
    descriptionAr: 'محفظة جلدية رفيعة ثنائية الطي مع حماية RFID.',
    storeId: 'leather-house',
    storeNameEn: 'Leather House',
    storeNameAr: 'بيت الجلود',
    image: bagImg,
    categoryEn: 'Accessories',
    categoryAr: 'إكسسوارات',
    storeCategoryId: 'lh-wallets',
    tags: ['leather', 'slim-wallet', 'rfid'],
    rating: 4.4,
    reviewCount: 298,
  },
  // ── Additional products for richer hashtag discovery ─────────────────────────
  {
    id: '13',
    nameEn: 'Woody Men\'s Cologne',
    nameAr: 'كولونيا رجالية خشبية',
    price: 189,
    originalPrice: 229,
    descriptionEn: 'A bold woody-spicy cologne with cedar, vetiver, and bergamot top notes.',
    descriptionAr: 'كولونيا رجالية جريئة بنفحات خشبية وتوابل مع أرز وفيتيفر وبرغموت.',
    storeId: 'scent-palace',
    storeNameEn: 'Scent Palace',
    storeNameAr: 'قصر العطور',
    image: perfumeImg,
    categoryEn: 'Perfumes',
    categoryAr: 'عطور',
    storeCategoryId: 'sp-mens',
    tags: ['mens-perfume', 'woody', 'cologne'],
    rating: 4.5,
    reviewCount: 88,
    isNew: true,
  },
  {
    id: '14',
    nameEn: 'Light Kids\' Cologne',
    nameAr: 'كولونيا أطفال خفيفة',
    price: 79,
    descriptionEn: 'Gentle floral and fruity fragrance crafted specially for children.',
    descriptionAr: 'عطر زهري وفاكهي لطيف مُصمَّم خصيصاً للأطفال.',
    storeId: 'scent-palace',
    storeNameEn: 'Scent Palace',
    storeNameAr: 'قصر العطور',
    image: perfumeImg,
    categoryEn: 'Perfumes',
    categoryAr: 'عطور',
    storeCategoryId: 'sp-kids',
    tags: ['kids-perfume', 'light', 'floral'],
    rating: 4.3,
    reviewCount: 54,
    isNew: true,
  },
  {
    id: '15',
    nameEn: 'Classic Oxford Shoes',
    nameAr: 'حذاء أوكسفورد كلاسيكي',
    price: 229,
    originalPrice: 289,
    descriptionEn: 'Hand-stitched leather Oxford shoes for formal and business occasions.',
    descriptionAr: 'حذاء جلد أوكسفورد مخاط يدوياً للمناسبات الرسمية وبيئة العمل.',
    storeId: 'step-up',
    storeNameEn: 'Step Up',
    storeNameAr: 'ستيب أب',
    image: sneakersImg,
    categoryEn: 'Shoes',
    categoryAr: 'أحذية',
    storeCategoryId: 'su-formal',
    tags: ['formal', 'leather-shoes', 'oxford'],
    rating: 4.6,
    reviewCount: 142,
    isFeatured: true,
  },
  {
    id: '16',
    nameEn: 'Sport Running Shoes',
    nameAr: 'حذاء جري رياضي',
    price: 189,
    originalPrice: 239,
    descriptionEn: 'Lightweight breathable running shoes with responsive cushioning.',
    descriptionAr: 'حذاء جري خفيف وقابل للتنفس مع تبطين متجاوب لأفضل أداء.',
    storeId: 'step-up',
    storeNameEn: 'Step Up',
    storeNameAr: 'ستيب أب',
    image: sneakersImg,
    categoryEn: 'Shoes',
    categoryAr: 'أحذية',
    storeCategoryId: 'su-sport',
    tags: ['sport', 'running', 'lightweight'],
    rating: 4.5,
    reviewCount: 267,
    isNew: true,
  },
  {
    id: '17',
    nameEn: 'True Wireless Earbuds',
    nameAr: 'سماعات لاسلكية حقيقية',
    price: 179,
    originalPrice: 219,
    descriptionEn: 'Compact TWS earbuds with 28-hour total playback and IPX5 sweat resistance.',
    descriptionAr: 'سماعات TWS صغيرة مع 28 ساعة تشغيل كاملة ومقاومة للعرق IPX5.',
    storeId: 'techzone',
    storeNameEn: 'TechZone',
    storeNameAr: 'تك زون',
    image: headphonesImg,
    categoryEn: 'Electronics',
    categoryAr: 'إلكترونيات',
    storeCategoryId: 'tc-audio',
    tags: ['wireless', 'audio', 'tws'],
    rating: 4.6,
    reviewCount: 318,
    isFeatured: true,
  },
  {
    id: '18',
    nameEn: 'Casual Denim Jacket',
    nameAr: 'جاكيت دينيم كاجوال',
    price: 139,
    descriptionEn: 'Classic straight-cut denim jacket — a timeless wardrobe staple.',
    descriptionAr: 'جاكيت دينيم بقصة مستقيمة كلاسيكية — أساسية خالدة في خزانة الملابس.',
    storeId: 'cozy-corner',
    storeNameEn: 'Cozy Corner',
    storeNameAr: 'الركن الدافئ',
    image: scarfImg,
    categoryEn: 'Fashion',
    categoryAr: 'أزياء',
    storeCategoryId: 'cc-casual',
    tags: ['casual', 'denim', 'jacket'],
    rating: 4.2,
    reviewCount: 73,
    isNew: true,
  },
];









