/**
 * Ad entity — mock API.
 *
 * Simulates the home/ads endpoints from
 * `docs/needed-endpoints-from-backend.md` (`home.md`, `ads.md`): the home
 * carousel, per-store carousels and per-category carousels. Mock data is copied
 * verbatim from the legacy monolith.
 */
import { Ad } from './model';

/** Home page carousel ads. TODO(migration): replaced by `GET /api/home/ads`. */
export const MOCK_ADS: Ad[] = [
  {
    id: 'ad-1',
    titleEn: 'Up to 40% Off Electronics',
    titleAr: 'خصم يصل إلى 40% على الإلكترونيات',
    subtitleEn: 'Latest gadgets at unbeatable prices — limited time!',
    subtitleAr: 'أحدث الأجهزة بأسعار لا تُضاهى — لفترة محدودة!',
    ctaEn: 'Shop Electronics',
    ctaAr: 'تسوق الإلكترونيات',
    emoji: '⚡',
    gradient: 'from-blue-600 to-indigo-700',
    linkType: 'category',
    linkValue: 'Electronics',
  },
  {
    id: 'ad-2',
    titleEn: 'Luxury Fragrances — New Arrivals',
    titleAr: 'عطور فاخرة — وصول جديد',
    subtitleEn: 'Discover exclusive Arabian scents crafted for royalty.',
    subtitleAr: 'اكتشف عطوراً عربية حصرية مُصنَّعة للملوك.',
    ctaEn: 'Explore Perfumes',
    ctaAr: 'استكشف العطور',
    emoji: '🌸',
    gradient: 'from-pink-500 to-rose-600',
    linkType: 'category',
    linkValue: 'Perfumes',
  },
  {
    id: 'ad-3',
    titleEn: 'Premium Watches — Swiss Made',
    titleAr: 'ساعات فاخرة — صناعة سويسرية',
    subtitleEn: 'Timeless elegance for every wrist. Explore our collection.',
    subtitleAr: 'أناقة خالدة لكل معصم. استعرض مجموعتنا.',
    ctaEn: 'View Watches',
    ctaAr: 'تصفح الساعات',
    emoji: '🕰️',
    gradient: 'from-amber-500 to-yellow-600',
    linkType: 'category',
    linkValue: 'Watches',
  },
  {
    id: 'ad-4',
    titleEn: 'Step Up — Footwear for Every Occasion',
    titleAr: 'ستيب أب — أحذية لكل مناسبة',
    subtitleEn: 'From casual sneakers to formal Oxfords. Find your perfect pair.',
    subtitleAr: 'من الأحذية الرياضية إلى الأوكسفورد الرسمي. اعثر على زوجك المثالي.',
    ctaEn: 'Shop Shoes',
    ctaAr: 'تسوق الأحذية',
    emoji: '👟',
    gradient: 'from-green-500 to-teal-600',
    linkType: 'category',
    linkValue: 'Shoes',
  },
  {
    id: 'ad-5',
    titleEn: 'Fashion & Knitwear — New Season',
    titleAr: 'أزياء وتريكو — موسم جديد',
    subtitleEn: 'Stay cozy and stylish with our latest winter collection.',
    subtitleAr: 'ابقَ دافئاً وأنيقاً مع أحدث مجموعة شتوية.',
    ctaEn: 'Explore Fashion',
    ctaAr: 'استكشف الأزياء',
    emoji: '🧣',
    gradient: 'from-orange-500 to-red-500',
    linkType: 'category',
    linkValue: 'Fashion',
  },
];

/** Store-specific carousel ads, keyed by store id. */
export const STORE_ADS: Record<string, Ad[]> = {
  techzone: [
    {
      id: 'tz-1',
      titleEn: 'TechZone — Flash Sale: 30% Off',
      titleAr: 'تك زون — تخفيضات فلاش: 30% خصم',
      subtitleEn: 'Grab the hottest gadgets before stock runs out!',
      subtitleAr: 'احصل على أحدث الأجهزة قبل نفاد المخزون!',
      ctaEn: 'Shop Now',
      ctaAr: 'تسوق الآن',
      emoji: '⚡',
      gradient: 'from-blue-600 to-cyan-600',
      linkType: 'store',
      linkValue: 'techzone',
    },
    {
      id: 'tz-2',
      titleEn: 'New: True Wireless Earbuds',
      titleAr: 'جديد: سماعات لاسلكية TWS',
      subtitleEn: '28-hour battery • IPX5 sweat-proof • Crystal clear sound.',
      subtitleAr: '28 ساعة بطارية • مقاومة العرق • صوت بلوري نقي.',
      ctaEn: 'Explore Audio',
      ctaAr: 'استكشف الصوتيات',
      emoji: '🎧',
      gradient: 'from-indigo-600 to-violet-700',
      linkType: 'store',
      linkValue: 'techzone',
    },
  ],
  'leather-house': [
    {
      id: 'lh-1',
      titleEn: 'Leather House — Handcrafted Luxury',
      titleAr: 'بيت الجلود — فخامة صنوعة يدوياً',
      subtitleEn: 'Every stitch tells a story. Genuine leather, timeless style.',
      subtitleAr: 'كل غرزة تحكي قصة. جلد أصيل، أناقة خالدة.',
      ctaEn: 'Browse Bags',
      ctaAr: 'تصفح الحقائب',
      emoji: '👜',
      gradient: 'from-amber-700 to-yellow-800',
      linkType: 'store',
      linkValue: 'leather-house',
    },
    {
      id: 'lh-2',
      titleEn: 'Slim Wallets — RFID Protected',
      titleAr: 'محافظ رفيعة — حماية RFID',
      subtitleEn: 'Carry less, live more. Full-grain leather bifold wallets.',
      subtitleAr: 'احمل أقل، عش أكثر. محافظ جلد طبيعي رفيعة.',
      ctaEn: 'Shop Wallets',
      ctaAr: 'تسوق المحافظ',
      emoji: '👛',
      gradient: 'from-stone-600 to-amber-800',
      linkType: 'store',
      linkValue: 'leather-house',
    },
  ],
  'time-gallery': [
    {
      id: 'tg-1',
      titleEn: 'Time Gallery — Gold Collection',
      titleAr: 'معرض الوقت — المجموعة الذهبية',
      subtitleEn: 'Swiss movement. Sapphire crystal. Timeless elegance.',
      subtitleAr: 'حركة سويسرية. كريستال ياقوتي. أناقة خالدة.',
      ctaEn: 'View Gold Watches',
      ctaAr: 'عرض الساعات الذهبية',
      emoji: '🥇',
      gradient: 'from-yellow-500 to-amber-600',
      linkType: 'store',
      linkValue: 'time-gallery',
    },
    {
      id: 'tg-2',
      titleEn: 'Silver Edition — Water Resistant',
      titleAr: 'الإصدار الفضي — مقاوم للماء',
      subtitleEn: 'Minimalist design, maximum precision. Up to 50m water resistance.',
      subtitleAr: 'تصميم بسيط، دقة قصوى. مقاوم للماء حتى 50م.',
      ctaEn: 'View Silver Watches',
      ctaAr: 'عرض الساعات الفضية',
      emoji: '🥈',
      gradient: 'from-slate-500 to-gray-700',
      linkType: 'store',
      linkValue: 'time-gallery',
    },
  ],
  'optic-style': [
    {
      id: 'os-1',
      titleEn: 'Optic Style — See the World Differently',
      titleAr: 'أوبتك ستايل — انظر للعالم بشكل مختلف',
      subtitleEn: 'UV400 polarized sunglasses. Lightweight. Iconic.',
      subtitleAr: 'نظارات شمسية مستقطبة UV400. خفيفة. أيقونية.',
      ctaEn: 'Shop Eyewear',
      ctaAr: 'تسوق النظارات',
      emoji: '🕶️',
      gradient: 'from-violet-600 to-purple-700',
      linkType: 'store',
      linkValue: 'optic-style',
    },
  ],
  'step-up': [
    {
      id: 'su-1',
      titleEn: 'Step Up — Walk in Style',
      titleAr: 'ستيب أب — امشِ بأناقة',
      subtitleEn: 'Sneakers, oxfords, and runners for every occasion.',
      subtitleAr: 'أحذية رياضية وأوكسفورد وجري لكل مناسبة.',
      ctaEn: 'Shop All Shoes',
      ctaAr: 'تسوق جميع الأحذية',
      emoji: '👟',
      gradient: 'from-green-600 to-emerald-700',
      linkType: 'store',
      linkValue: 'step-up',
    },
    {
      id: 'su-2',
      titleEn: 'New: Sport Running Collection',
      titleAr: 'جديد: مجموعة الجري الرياضي',
      subtitleEn: 'Lightweight. Breathable. Built for performance.',
      subtitleAr: 'خفيفة. قابلة للتنفس. مصممة للأداء العالي.',
      ctaEn: 'Explore Running',
      ctaAr: 'استكشف الجري',
      emoji: '🏃',
      gradient: 'from-teal-500 to-green-700',
      linkType: 'store',
      linkValue: 'step-up',
    },
  ],
  'scent-palace': [
    {
      id: 'sp-1',
      titleEn: 'Scent Palace — Arabian Oud Collection',
      titleAr: 'قصر العطور — مجموعة العود العربي',
      subtitleEn: 'Rich oud blended with amber and sandalwood. A royal experience.',
      subtitleAr: 'عود غني ممزوج بالعنبر وخشب الصندل. تجربة ملكية.',
      ctaEn: 'Shop Oud',
      ctaAr: 'تسوق العود',
      emoji: '🧴',
      gradient: 'from-rose-700 to-pink-800',
      linkType: 'store',
      linkValue: 'scent-palace',
    },
    {
      id: 'sp-2',
      titleEn: "New Season — Women's & Kids' Fragrances",
      titleAr: 'موسم جديد — عطور نسائية وأطفال',
      subtitleEn: "Delicate floral musks and gentle kids' colognes.",
      subtitleAr: 'مسكات زهرية رقيقة وعطور أطفال لطيفة.',
      ctaEn: 'Explore Fragrances',
      ctaAr: 'استكشف العطور',
      emoji: '🌸',
      gradient: 'from-pink-500 to-rose-600',
      linkType: 'store',
      linkValue: 'scent-palace',
    },
  ],
  'cozy-corner': [
    {
      id: 'cc-1',
      titleEn: 'Cozy Corner — Winter Collection',
      titleAr: 'الركن الدافئ — مجموعة الشتاء',
      subtitleEn: 'Soft merino wool scarves and knitwear for cold days.',
      subtitleAr: 'وشاحات صوف ميرينو ناعمة وتريكو دافئ لأيام البرد.',
      ctaEn: 'Shop Winter',
      ctaAr: 'تسوق الشتاء',
      emoji: '🧣',
      gradient: 'from-orange-600 to-red-700',
      linkType: 'store',
      linkValue: 'cozy-corner',
    },
    {
      id: 'cc-2',
      titleEn: 'Casual Denim — Timeless Wardrobe',
      titleAr: 'دينيم كاجوال — خزانة ملابس خالدة',
      subtitleEn: 'Classic straight-cut denim jackets. Always in style.',
      subtitleAr: 'جاكيتات دينيم بقصة مستقيمة كلاسيكية. دائماً في الموضة.',
      ctaEn: 'Explore Casual',
      ctaAr: 'استكشف الكاجوال',
      emoji: '👕',
      gradient: 'from-amber-500 to-orange-600',
      linkType: 'store',
      linkValue: 'cozy-corner',
    },
  ],
};

/** Category-specific carousel ads, keyed by platform category (English). */
export const CATEGORY_ADS: Record<string, Ad[]> = {
  Electronics: [
    {
      id: 'cat-elec-1',
      titleEn: 'Electronics — Up to 40% Off',
      titleAr: 'إلكترونيات — خصم يصل إلى 40%',
      subtitleEn: 'Phones, earbuds, wearables and more — at unbeatable prices.',
      subtitleAr: 'هواتف، سماعات، أجهزة ذكية والمزيد — بأسعار لا تُضاهى.',
      ctaEn: 'Shop Electronics',
      ctaAr: 'تسوق الإلكترونيات',
      emoji: '⚡',
      gradient: 'from-blue-600 to-indigo-700',
      linkType: 'category',
      linkValue: 'Electronics',
    },
    {
      id: 'cat-elec-2',
      titleEn: 'New Arrivals: Wearable Tech',
      titleAr: 'وصل حديثاً: أجهزة قابلة للارتداء',
      subtitleEn: 'Smart fitness bands, TWS earbuds, and flagship phones.',
      subtitleAr: 'أساور لياقة ذكية، سماعات TWS، وهواتف رائدة.',
      ctaEn: 'Discover Now',
      ctaAr: 'اكتشف الآن',
      emoji: '📱',
      gradient: 'from-cyan-500 to-blue-600',
      linkType: 'category',
      linkValue: 'Electronics',
    },
  ],
  Accessories: [
    {
      id: 'cat-acc-1',
      titleEn: 'Accessories — Curated Collections',
      titleAr: 'إكسسوارات — مجموعات مختارة',
      subtitleEn: 'Bags, eyewear, wallets — handpicked for you.',
      subtitleAr: 'حقائب، نظارات، محافظ — مختارة خصيصاً لك.',
      ctaEn: 'Browse Accessories',
      ctaAr: 'تصفح الإكسسوارات',
      emoji: '💎',
      gradient: 'from-purple-600 to-violet-700',
      linkType: 'category',
      linkValue: 'Accessories',
    },
    {
      id: 'cat-acc-2',
      titleEn: 'Leather Goods — New Season',
      titleAr: 'منتجات جلدية — موسم جديد',
      subtitleEn: 'Premium full-grain leather bags and RFID wallets.',
      subtitleAr: 'حقائب جلد طبيعي فاخرة ومحافظ مع حماية RFID.',
      ctaEn: 'Explore Leather',
      ctaAr: 'استكشف الجلود',
      emoji: '👜',
      gradient: 'from-violet-500 to-purple-700',
      linkType: 'category',
      linkValue: 'Accessories',
    },
  ],
  Watches: [
    {
      id: 'cat-wat-1',
      titleEn: 'Luxury Watches — Swiss Precision',
      titleAr: 'ساعات فاخرة — دقة سويسرية',
      subtitleEn: 'Gold and silver timepieces crafted for the discerning.',
      subtitleAr: 'ساعات ذهبية وفضية مُصنَّعة لذوي الذوق الرفيع.',
      ctaEn: 'View Watches',
      ctaAr: 'تصفح الساعات',
      emoji: '🕰️',
      gradient: 'from-amber-500 to-yellow-600',
      linkType: 'category',
      linkValue: 'Watches',
    },
    {
      id: 'cat-wat-2',
      titleEn: 'Minimalist Silver Edition',
      titleAr: 'الإصدار الفضي البسيط',
      subtitleEn: 'Slim profile. Sapphire glass. Water resistant to 50m.',
      subtitleAr: 'حجم رفيع. زجاج ياقوتي. مقاوم للماء حتى 50م.',
      ctaEn: 'Shop Now',
      ctaAr: 'تسوق الآن',
      emoji: '⌚',
      gradient: 'from-slate-500 to-yellow-700',
      linkType: 'category',
      linkValue: 'Watches',
    },
  ],
  Shoes: [
    {
      id: 'cat-sho-1',
      titleEn: 'Footwear — Every Occasion',
      titleAr: 'أحذية — لكل مناسبة',
      subtitleEn: 'Casual sneakers, formal oxfords, and sport runners.',
      subtitleAr: 'أحذية رياضية كاجوال، أوكسفورد رسمية، وأحذية جري.',
      ctaEn: 'Shop Shoes',
      ctaAr: 'تسوق الأحذية',
      emoji: '👟',
      gradient: 'from-green-600 to-teal-700',
      linkType: 'category',
      linkValue: 'Shoes',
    },
    {
      id: 'cat-sho-2',
      titleEn: 'Sport Running — New Collection',
      titleAr: 'الجري الرياضي — مجموعة جديدة',
      subtitleEn: 'Lightweight. Breathable. Responsive cushioning.',
      subtitleAr: 'خفيفة. قابلة للتنفس. تبطين متجاوب.',
      ctaEn: 'Explore Running',
      ctaAr: 'استكشف الجري',
      emoji: '🏃',
      gradient: 'from-emerald-500 to-green-700',
      linkType: 'category',
      linkValue: 'Shoes',
    },
  ],
  Perfumes: [
    {
      id: 'cat-per-1',
      titleEn: 'Arabian Fragrances — New Arrivals',
      titleAr: 'عطور عربية — وصول جديد',
      subtitleEn: 'Exclusive oud, musk, and floral scents from Scent Palace.',
      subtitleAr: 'عطور عود وتشك وزهرية حصرية من قصر العطور.',
      ctaEn: 'Explore Perfumes',
      ctaAr: 'استكشف العطور',
      emoji: '🌸',
      gradient: 'from-pink-600 to-rose-700',
      linkType: 'category',
      linkValue: 'Perfumes',
    },
    {
      id: 'cat-per-2',
      titleEn: "Kids' Fragrances — Gentle & Safe",
      titleAr: 'عطور الأطفال — لطيفة وآمنة',
      subtitleEn: 'Light floral and fruity scents designed for little ones.',
      subtitleAr: 'عطور زهرية وفاكهية خفيفة مُصممة للأطفال.',
      ctaEn: "Shop Kids' Scents",
      ctaAr: 'تسوق عطور الأطفال',
      emoji: '🧒',
      gradient: 'from-rose-400 to-pink-600',
      linkType: 'category',
      linkValue: 'Perfumes',
    },
  ],
  Fashion: [
    {
      id: 'cat-fas-1',
      titleEn: 'Fashion — New Winter Season',
      titleAr: 'أزياء — موسم الشتاء الجديد',
      subtitleEn: 'Cozy knitwear, denim, and more — stay stylish all season.',
      subtitleAr: 'تريكو دافئ، دينيم، والمزيد — ابقَ أنيقاً طوال الموسم.',
      ctaEn: 'Explore Fashion',
      ctaAr: 'استكشف الأزياء',
      emoji: '👗',
      gradient: 'from-orange-500 to-red-600',
      linkType: 'category',
      linkValue: 'Fashion',
    },
    {
      id: 'cat-fas-2',
      titleEn: 'Classic Denim — Timeless Style',
      titleAr: 'دينيم كلاسيكي — أناقة خالدة',
      subtitleEn: 'Straight-cut denim jackets. A wardrobe essential.',
      subtitleAr: 'جاكيتات دينيم بقصة مستقيمة. أساسي في كل خزانة.',
      ctaEn: 'Shop Denim',
      ctaAr: 'تسوق الدينيم',
      emoji: '🧣',
      gradient: 'from-red-500 to-orange-600',
      linkType: 'category',
      linkValue: 'Fashion',
    },
  ],
};

/** Simulates `GET /api/home/ads`. */
export async function getHomeAds(): Promise<Ad[]> {
  return new Promise(resolve => setTimeout(() => resolve(MOCK_ADS), 100));
}

/** Simulates `GET /api/stores/{storeId}/ads`. */
export async function getStoreAds(storeId: string): Promise<Ad[]> {
  return new Promise(resolve =>
    setTimeout(() => resolve(STORE_ADS[storeId] ?? []), 100)
  );
}

/** Simulates `GET /api/categories/{categoryEn}/ads`. */
export async function getCategoryAds(categoryEn: string): Promise<Ad[]> {
  return new Promise(resolve =>
    setTimeout(() => resolve(CATEGORY_ADS[categoryEn] ?? []), 100)
  );
}
